### ISSUE TITLE
IOS 加起来 启动xcode 报错

### ISSUE THREAD

**Issue by AdelaDella** [lyxia/MyRNStartKit#1]
![b3f9f26d-e59a-474f-8654-d95de186bd91](https://user-images.githubusercontent.com/33622382/37595390-9c6e30f6-2bb3-11e8-9346-84d6586e102f.png)

**Comment by lyxia** [comment]
1、git clone https://github.com/lyxia/MyRNStartKit.git
2、cd MyRNStartKit
3、yarn install
4、react-native run-ios
运行成功后点击： 【点击登录】->【Tabbar（示例）】->【UseCustomKeyboard】

我做上面一系列操作没有遇到问题
