### ISSUE TITLE
求指教，自定义键盘可以剥离出来关键文件么？

### ISSUE THREAD

**Issue by orzhtml** [lyxia/MyRNStartKit#2]
例如：customKeyboard.js 

我发现还要结合 安卓和ios原生才行

**Comment by lyxia** [comment]
可以查看以下仓库：
https://github.com/lyxia/react-native-yusha-customKeyboard

**Comment by orzhtml** [comment]
因为项目已经有一套自定义键盘了，我能用自己的注册到 customKeyboard 吗
