### ISSUE TITLE
脚手架的2个小问题

### ISSUE THREAD

**Issue by orzhtml** [lyxia/MyRNStartKit#4]
1、模拟器debug后，键盘无法弹起（我参考了react-native-yusha-customKeyboard的customKeyboard.js，解决了debug键盘弹不出来的问题）。
2、安卓运行不起来，是否能有更详细的配置环境描述。
3、Remote debugger is in a background tab which may cause apps to perform slowly. Fix this by foregrounding the tab (or opening it in a separate window).
视乎性能上有欠缺，问题不大。
4、按键的事件绑定上 requestAnimationFrame ，有什么作用呢？
RN - 0.44.3

**Comment by lyxia** [comment]
问题2：给出具体问题
问题3：这是RN都有的，debug下，要把debug页面放前台就好，也可以使用:https://github.com/jhen0409/react-native-debugger
问题4：这是一个性能优化点，可参考：https://reactnative.cn/docs/0.51/performance.html#content

**Comment by orzhtml** [comment]
customKeyboard.js  
_onChangeText = (text) => {
	this.setState({text});
        this.props.onChangeText && this.props.onChangeText(text);
}
赋值后才执行回调，导致行为不同步，建议如下更改：
_onChangeText = (text) => {
		this.setState({text}, () => {
			this.props.onChangeText && this.props.onChangeText(text);
		});
	}
或者直接去掉 this.setState({text});

**Comment by orzhtml** [comment]
安卓的报错是：
Cannot read property 'install' of undefined

**Comment by lyxia** [comment]
我运行android没有这种保存，建议load本地服务器，不要使用离线包，或者打开debug模式调调

**Comment by lyxia** [comment]
我运行android没有这种报错，建议load本地服务器，不要使用离线包，或者打开debug模式调调

**Comment by orzhtml** [comment]
已经解决了，谢谢。
