### ISSUE TITLE
监听输入的问题

### ISSUE THREAD

**Issue by orzhtml** [lyxia/MyRNStartKit#5]
insertText(this.props.tag, value);

在键盘输入的时候能拿到 tag 和 value

但是无法拿到 TextInput 已输入的值

求解？

因为我要对输入的数字进行判断。例如 输入的是金额格式：1234.66    
我需要已经输入的数值
例如
_onInput = (value) => {
    if ('1234.66'.indexOf('.') >= 0 && value == '.') {
        return;
    } else {
          this.insertTextRequest = requestAnimationFrame(() => {
		insertText(this.props.tag, value);
	});
   }
}

怎么能拿到  TextInput 的 value

**Comment by lyxia** [comment]
https://reactnative.cn/docs/0.51/textinput.html#content
里面有提到：最简单的用法就是丢一个TextInput到应用里，然后订阅它的onChangeText事件来读取用户的输入。注意，从TextInput里取值这就是目前唯一的做法！也就是使用在onChangeText中用setState把用户的输入写入到state中，然后在需要取值的地方从this.state中取出值。

**Comment by lyxia** [comment]
源码：
  render() {
    const { customKeyboardType, ...others } = this.props;
    return <TextInput {...others} ref={this.onRef}/>;
  }

所以用法同TextInput

**Comment by orzhtml** [comment]
这个明白，缺点是， this.state 重新赋值，会闪烁（删除多余的输入），并且判断会更复杂
例如：   12345.64.99
正常来说，能拦截第二个小数点就方便了
另外还有999999999999.99  用户只能输入的金额不能超过这个位数，包括小数点后两位，如果能拦截按键，那么判断方式也能更简洁。

**Comment by lyxia** [comment]
对于官方的TextInput能拦截按键吗？

**Comment by orzhtml** [comment]
rn：臣妾做不到啊
